spring:
  application:
    name: zonas-espacios

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/zonas_espacios?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:admin123}

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET:miClaveSecretaSuperSeguraParaJWT123456789}
  issuer: ${JWT_ISSUER:http://localhost:8080}

audit:
  exchange: ${RABBITMQ_EXCHANGE:exchange_audit}
  routing-key: ${RABBITMQ_ROUTING_KEY:routing_audit}