spring.application.name=usuarios

server.address=0.0.0.0
server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/usuarios_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:true}

# JWT / OAuth centralizado
jwt.secret=${JWT_SECRET:miClaveSecretaSuperSeguraParaJWT123456789}
jwt.expiration=${JWT_EXPIRATION:86400000}
jwt.issuer=${JWT_ISSUER:http://localhost:8080}

# RabbitMQ (auditoria)
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin123}
audit.exchange=${RABBITMQ_EXCHANGE:exchange_audit}
audit.routing-key=${RABBITMQ_ROUTING_KEY:routing_audit}
